### ISSUE TITLE
Backend is broken with latest errbot API

### ISSUE THREAD

**Issue by TomaszDom** [AoiKuiyuyou/AoikRocketChatErrbot#1]
When trying to respond:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/errbot-5.1.2-py3.5.egg/errbot/core.py", line 461, in _execute_and_send
    self.send_simple_reply(msg, self.process_template(template_name, reply), private, threaded)
  File "/usr/local/lib/python3.5/dist-packages/errbot-5.1.2-py3.5.egg/errbot/core.py", line 198, in send_simple_reply
    reply = self.build_reply(msg, text, private=private, threaded=threaded)
TypeError: build_reply() got an unexpected keyword argument 'threaded'
`

I found a similar issue with another backend:

https://github.com/errbotio/err-backend-gitter/issues/30

**Comment by cardoso** [comment]
@AoiKuiyuyou seems to be inactive for several months. I've duplicated this repo and fixed this issue.

[cardoso/errbot-rocketchat](https://github.com/cardoso/errbot-rocketchat)

I'll see if there's enough interest for RocketChat to officially support this.
